# numpy  and Pandas

In [1]:
import numpy as np
a1=np.array([1,2,3,4,5])
print(a1);
print(type(a1));

a2=np.array([[1,2,3,56,8],[1,8,65,4,3]])
print(a2)
print(a2.shape)
## reshaping of an array
a3=a2.reshape(5,2)
print(a3)
print(a3.transpose())

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[ 1  2  3 56  8]
 [ 1  8 65  4  3]]
(2, 5)
[[ 1  2]
 [ 3 56]
 [ 8  1]
 [ 8 65]
 [ 4  3]]
[[ 1  3  8  8  4]
 [ 2 56  1 65  3]]


In [2]:
## matrix and array operation
n1=np.array([[1,2,4,3,65,12],[4,3,5,7,93,12]])
n2=np.array([[7,5,87,4,3,2],[56,4,7,9,1,4]])
print(n1+n2)
print(n1*n2)
print(n1.dot(n2.reshape(6,2)))
print(np.zeros(11,dtype = int))
print(np.zeros((2,5),dtype = int))
print(n1.sum())
print(n1.min(),n1.max())

[[ 8  7 91  7 68 14]
 [60  7 12 16 94 16]]
[[  7  10 348  12 195  24]
 [224  12  35  63  93  48]]
[[ 828  666]
 [1359  955]]
[0 0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0 0]
 [0 0 0 0 0]]
211
1 93


## Pandas

##### Series- 1D labelled array can hold any data type (only index)
##### DataFrame- 2D labelled DS . like spredsheet or SQL Table (coloumn and index)

In [3]:
import pandas as pd

df=pd.read_csv("../DS/mtcars.csv")
print("**************************Data Frame***************************\n",df,"\n\n")
print("************************Data Frame shape***********************\n\n",df.shape,"\n\n")
print("************************Data Frame column**********************\n\n",df.columns,"\n\n")
print("************************Data Frame head************************\n\n",df.head(4),"\n\n")
print("************************Data Frame tail************************\n\n",df.tail(4),"\n\n")
print("************************Data Frame info************************\n\n")
print(df.info(),"\n\n")
print("************************Data Frame Describe************************\n\n",df.describe(),"\n\n")


**************************Data Frame***************************
              Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   

In [4]:
### Accessing Coloumn

#####Accessing by name
print(df[["gear","qsec"]].head(2),"\n\n")


#####Accessing by index
print(df.iloc[1:2],"\n\n")
print(df.iloc[1:3,0:4],"\n\n")
print(df.iloc[:3,[0,2,4]],"\n\n")

   gear   qsec
0     4  16.46
1     4  17.02 


      Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
1  Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4   

   carb  
1     4   


      Unnamed: 0   mpg  cyl   disp
1  Mazda RX4 Wag  21.0    6  160.0
2     Datsun 710  22.8    4  108.0 


      Unnamed: 0  cyl   hp
0      Mazda RX4    6  110
1  Mazda RX4 Wag    6  110
2     Datsun 710    4   93 




In [5]:
### creating and updating column
df['col12']=1 # creating coloumn as col12 doesnt exist else update
print(df.iloc[:2,12:])

df['new cell']=df['wt']*df['cyl']
print(df.iloc[:2,12:])

### deleting column 
del df['col12']
print(df.iloc[:2,12:])

   col12
0      1
1      1
   col12  new cell
0      1     15.72
1      1     17.25
   new cell
0     15.72
1     17.25


In [6]:

def lower_p(val):
    return str(val).lower();

In [7]:
### type cast
df.columns.values[0] = "Car_Name"
print(df.iloc[:2]['Car_Name'].str.upper()+" -NEW")
### custom operation on each entry
print(df.iloc[:2]['Car_Name'].apply(lower_p))

0        MAZDA RX4 -NEW
1    MAZDA RX4 WAG -NEW
Name: Car_Name, dtype: object
0        mazda rx4
1    mazda rx4 wag
Name: Car_Name, dtype: object


In [8]:
### Filtering 
df_new= df[(df['gear'] >= 4) & (df['am']>=1) & (df['vs']>=1)]
print(df_new)
#### Ascending column wise
print(df_new.sort_values(["gear","hp"],ascending=[0,1]))
#### unique value in the column
print(df_new[0:]["gear"].unique())

          Car_Name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
2       Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
17        Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
18     Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
19  Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4   
25       Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4   

    carb  new cell  
2      1     9.280  
17     1     8.800  
18     2     6.460  
19     1     7.340  
25     1     7.740  
27     2     6.052  
31     2    11.120  
          Car_Name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   
18     Honda Civic  30.4    4   75.7   52

In [9]:
#### group by
df_g=df.groupby(['gear','hp'],as_index =False)["mpg"].mean()
print(df_g[:8])

   gear   hp    mpg
0     3   97  21.50
1     3  105  18.10
2     3  110  21.40
3     3  150  15.35
4     3  175  18.95
5     3  180  16.30
6     3  205  10.40
7     3  215  10.40
